% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Nov-2016 14:33:42
%  MATLAB version: 8.6.0.267246 (R2015b)
% -------------------------------------------------------------------
saveVarsMat = load('WB_test28_4900.mat');

WB_small = saveVarsMat.WB_small; % <4900x784 double> too many elements

clear saveVarsMat;
